spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/tp_music
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  mail:  # ✅ 正确：mail 是 spring 下的一级配置
    host: smtp.qq.com
    port: 465
    username: 1643489909@qq.com
    password: iyffpjugmarzeefj  # QQ邮箱授权码
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true

logging:
  level:
    com.lsy: trace

server:
  port: 8888
